name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: komorebi-switcher-windows-pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
          path: target/debug/komorebi-switcher.exe
          overwrite: true

  build-macos:
    runs-on: macos-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: komorebi-switcher-macos-pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
          path: target/debug/komorebi-switcher
          overwrite: true

  upload-pr-meta:
    if: github.event_name == 'pull_request'
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Write PR metadata
        run: |
          mkdir -p pr-meta
          cat > pr-meta/pr-meta.json <<EOF
          {
            "pr_number": "${{ github.event.number }}",
            "commit_sha": "${{ github.event.pull_request.head.sha }}",
            "windows_artifact_id": "${{ needs.build-windows.outputs.artifact-id }}",
            "macos_artifact_id": "${{ needs.build-macos.outputs.artifact-id }}"
          }
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: pr-meta
          path: pr-meta/
          overwrite: true
